config/routes.rb
Rails.application.routes.draw do
  root 'lightsabers#index'
  resources :lightsabers


end

app/models/lightsaber.rb
class Lightsaber < ActiveRecord::Base
  validates :name, :presence => true
  validates :color, :presence => true

  def self.get_random_gif
    [1,2,3,4,5,6].sample
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lightsabers_controller.rb
class LightsabersController < ApplicationController
  def index
    @lightsabers = Lightsaber.all
  end

  def show
    @lightsaber = Lightsaber.find(params[:id])
    @random_gif = Lightsaber.get_random_gif
  end

  def new
    @lightsaber = Lightsaber.new
  end

  def create
    @lightsaber = Lightsaber.new(lightsaber_params)

    if @lightsaber.save
      flash[:success] = "Jedi was successfully created"
      redirect_to lightsaber_path(@lightsaber)
    else
      render :new
    end
  end

  def edit
    @lightsaber = Lightsaber.find(params[:id])
  end

  def update
    @lightsaber = Lightsaber.find(params[:id])

    if @lightsaber.update(lightsaber_params)
      flash[:success] = "Jedi was successfully updated"
      redirect_to lightsaber_path(@lightsaber)
    else
      render :edit
    end
  end

  def destroy
    Lightsaber.destroy(params[:id])
    flash[:success] = "Jedi was successfully deleted"
    redirect_to lightsabers_path
  end


  private

  def lightsaber_params
    params.require(:lightsaber).permit(:name, :color)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title LightsaberPractice
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse
      = link_to "Join the Force!", lightsabers_path, class: "navbar-brand"


    .container
      -flash.each do |name, msg|
        =content_tag :div, msg, class: "alert alert-success"

      = yield

app/views/lightsabers/_form.html.haml
=form_for @lightsaber do |f|
  - if @lightsaber.errors.any?
    .alert.alert-danger
      %h3
        = pluralize(@lightsaber.errors.count, "error")
        prohibited this Jedi from being saved:

      %ul
        - @lightsaber.errors.full_messages.each do |message|
          %li
            = message

  =f.label :name
  =f.text_field :name
  %br

    =f.label :color
    =f.text_field :color
  %br

    =f.submit name_of_button, class: "btn btn-info"

%br

= image_tag("lightsaber_horizontal.jpeg")

app/views/lightsabers/edit.html.haml
%h1
  .page-header
    Edit Jedi

= render partial:"form", locals: {name_of_button: "Update Jedi"}

app/views/lightsabers/index.html.haml
%h1
  .page-header
    All Jedi

%table.table
  %thead
    %tr
      %th{:colspan => "2"}
        %strong Jedi Stats

  %tbody
    - @lightsabers.each do |lightsaber|
      %tr
        %td.col-md-10
          %em Jedi Name:
          = link_to lightsaber.name, lightsaber_path(lightsaber)
          %br
          %em Color:
          =lightsaber.color
        %td.text-right
          = link_to "Edit", edit_lightsaber_path(lightsaber), class: "btn btn-default"
          = link_to "Delete", lightsaber_path(lightsaber), class: "btn btn-danger", method: :delete, data: {confirm: "Do you really want to leave the force?"}

= link_to "New Jedi", new_lightsaber_path(@lightsaber), class: "btn btn-success"

app/views/lightsabers/new.html.haml
%h1
  .page-header
    New Jedi

= render partial:"form", locals: {name_of_button: "Join the Force"}

app/views/lightsabers/show.html.haml
%h1
  .page-header
    = @lightsaber.name


= image_tag("#{@random_gif}.gif")

%br
%em Jedi Name:
=@lightsaber.name
%br
%em Color:
=@lightsaber.color

%br

= link_to "Edit", edit_lightsaber_path(@lightsaber), class: "btn btn-info"
= link_to "Delete", lightsaber_path(@lightsaber), class: "btn btn-danger", method: :delete, data: {confirm: "Do you really want to leave the force?"}

%hr
=link_to "All Jedi", lightsabers_path, class: "btn btn-info"